# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    restoreNugetPackages: true

- task: CopyFiles@2
  inputs:
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'test_artifact'
        publishLocation: 'Container'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'Unit Tests'
    diagnosticsEnabled: true


    
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    MachineNames: '10.2.17.115'
    AdminUserName: 'DEV2\testpipeline'
    AdminPassword: 'Fruittowers2019'
    TargetPath: 'C:\test'